[package]
name = "lantern-signer-passkey"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Lantern WebAuthn / FIDO2 / passkey signer"

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
